main:
  listeners:
    - scheme: http
      port: 80
    - scheme: https
      port: 443

metrics:
  listeners:
    - scheme: http
      port: 80

db:
  type: postgres
  uri: jdbc:postgresql://host:port/database
  # The password will be injected from another file
  #password:

root: extra
